This is makeindex, version 2.17 [TeX Live 2026/dev] (kpathsea + Thai support).
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....done (540 entries accepted, 0 rejected).
Sorting entries.......done (5394 comparisons).
Generating output file main.acr....done (293 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
